import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <head>
        <meta
          name="keywords"
          content="Guiabolso, Controle financeiro pessoal, Aplicativo de finanças pessoais, Orçamento financeiro, Gestão de gastos, Planejamento financeiro, Economia de dinheiro, Investimentos pessoais, Contas bancárias, Ferramentas financeiras, Dicas de economia, Finanças pessoais online, Gerenciador de gastos, Conciliação bancária, Controle de despesas"
        ></meta>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
